/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import proyecto.pkg1.ComponentesConectados;
import proyecto.pkg1.Grafo;
import proyecto.pkg1.MatrizAdyacencia;

/**
 *
 * @author emilianaplaz
 */
public class VentanaFuncionesLista extends javax.swing.JFrame {
    
    public static MenuPrincipal v1;

    /**
     * Creates new form VentanaFuncionesLista
     */
    public VentanaFuncionesLista(MenuPrincipal v1) {
        this.v1=v1;
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        atras = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        identificar_componentes = new javax.swing.JButton();
        mostrar_grafo = new javax.swing.JButton();
        modificar_lista = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atras.setBackground(new java.awt.Color(0, 51, 102));
        atras.setFont(new java.awt.Font("Kohinoor Bangla", 1, 14)); // NOI18N
        atras.setText("< Atrás");
        atras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 60, -1));

        lbl1.setBackground(new java.awt.Color(216, 235, 255));
        lbl1.setFont(new java.awt.Font("Kohinoor Bangla", 1, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 51, 102));
        lbl1.setText("FUNCIONES");
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        identificar_componentes.setBackground(new java.awt.Color(0, 51, 102));
        identificar_componentes.setFont(new java.awt.Font("Kohinoor Bangla", 1, 14)); // NOI18N
        identificar_componentes.setText("Componentes fuertemente conectados ");
        identificar_componentes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        identificar_componentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificar_componentesActionPerformed(evt);
            }
        });
        jPanel2.add(identificar_componentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 300, -1));

        mostrar_grafo.setBackground(new java.awt.Color(0, 51, 102));
        mostrar_grafo.setFont(new java.awt.Font("Kohinoor Bangla", 1, 14)); // NOI18N
        mostrar_grafo.setText("Mostrar Grafo");
        mostrar_grafo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mostrar_grafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrar_grafoActionPerformed(evt);
            }
        });
        jPanel2.add(mostrar_grafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 300, -1));

        modificar_lista.setBackground(new java.awt.Color(0, 51, 102));
        modificar_lista.setFont(new java.awt.Font("Kohinoor Bangla", 1, 14)); // NOI18N
        modificar_lista.setText("Modificar Lista");
        modificar_lista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificar_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_listaActionPerformed(evt);
            }
        });
        jPanel2.add(modificar_lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 360, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificar_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_listaActionPerformed
    VentanaModificarLista modificar = new VentanaModificarLista (this);
    modificar.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_modificar_listaActionPerformed

    private void identificar_componentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificar_componentesActionPerformed
        // TODO add your handling code here:
        MatrizAdyacencia matriz = new MatrizAdyacencia();
        Grafo grafo = new Grafo();
        ComponentesConectados comp = new ComponentesConectados();
        matriz.crear_matriz();
        grafo.crear_grafo();
        comp.display();
        
        
    }//GEN-LAST:event_identificar_componentesActionPerformed

    private void mostrar_grafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_grafoActionPerformed
        // TODO add your handling code here:
        MatrizAdyacencia matriz = new MatrizAdyacencia();
        Grafo grafo = new Grafo();
        matriz.crear_matriz();
        grafo.crear_grafo();

    
    }//GEN-LAST:event_mostrar_grafoActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
        v1.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFuncionesLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFuncionesLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFuncionesLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFuncionesLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFuncionesLista(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton identificar_componentes;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JButton modificar_lista;
    private javax.swing.JButton mostrar_grafo;
    // End of variables declaration//GEN-END:variables
}
