/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import proyecto.pkg1.FuncionesGrafo;
import static proyecto.pkg1.FuncionesGrafo.relacionExistente;
import proyecto.pkg1.MatrizAdyacencia;

/**
 *
 * @author emilianaplaz
 */
public class VentanaAgregarConexion extends javax.swing.JFrame {
    
    public static VentanaModificarLista v3;
    /**
     * Creates new form VentanaAgregarConexion
     */
    public VentanaAgregarConexion(VentanaModificarLista v3) {
        MatrizAdyacencia ma=new MatrizAdyacencia();
        ma.crear_matriz();
        this.v3=v3;
        initComponents();
        this.setLocationRelativeTo(null);
        lbl_rel_agg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        atras = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        agg_rel_btn = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        entry_nueva_relacion_1 = new javax.swing.JComboBox<>();
        entry_nueva_relacion_2 = new javax.swing.JComboBox<>();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl_rel_agg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atras.setBackground(new java.awt.Color(0, 51, 102));
        atras.setFont(new java.awt.Font("Kohinoor Bangla", 1, 14)); // NOI18N
        atras.setText("<Atrás");
        atras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 60, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agg_rel_btn.setBackground(new java.awt.Color(0, 51, 102));
        agg_rel_btn.setFont(new java.awt.Font("Kohinoor Bangla", 1, 14)); // NOI18N
        agg_rel_btn.setText("Agregar relación");
        agg_rel_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agg_rel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agg_rel_btnActionPerformed(evt);
            }
        });
        jPanel2.add(agg_rel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 230, -1));

        lbl1.setFont(new java.awt.Font("Kohinoor Bangla", 1, 18)); // NOI18N
        lbl1.setForeground(new java.awt.Color(0, 51, 102));
        lbl1.setText("Ingrese una nueva relación");
        jPanel2.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbl2.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        lbl2.setForeground(new java.awt.Color(102, 102, 102));
        lbl2.setText("El orden de los usuarios es relevante");
        jPanel2.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 220, -1));

        entry_nueva_relacion_1.setModel(new javax.swing.DefaultComboBoxModel(MatrizAdyacencia.getUsuarios()));
        entry_nueva_relacion_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entry_nueva_relacion_1ActionPerformed(evt);
            }
        });
        jPanel2.add(entry_nueva_relacion_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, -1));

        entry_nueva_relacion_2.setModel(new javax.swing.DefaultComboBoxModel(MatrizAdyacencia.getUsuarios()));
        entry_nueva_relacion_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entry_nueva_relacion_2ActionPerformed(evt);
            }
        });
        jPanel2.add(entry_nueva_relacion_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 200, -1));

        lbl3.setFont(new java.awt.Font("Kohinoor Bangla", 0, 12)); // NOI18N
        lbl3.setForeground(new java.awt.Color(102, 102, 102));
        lbl3.setText("Usuario 1:");
        jPanel2.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lbl4.setFont(new java.awt.Font("Kohinoor Bangla", 0, 12)); // NOI18N
        lbl4.setForeground(new java.awt.Color(102, 102, 102));
        lbl4.setText("Usuario 2:");
        jPanel2.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lbl_rel_agg.setBackground(new java.awt.Color(255, 255, 255));
        lbl_rel_agg.setFont(new java.awt.Font("Kohinoor Bangla", 1, 18)); // NOI18N
        lbl_rel_agg.setForeground(new java.awt.Color(0, 51, 102));
        lbl_rel_agg.setText("Relación agregada!");
        jPanel2.add(lbl_rel_agg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agg_rel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agg_rel_btnActionPerformed
        // TODO add your handling code here:
        
        if (entry_nueva_relacion_1.getSelectedItem()==entry_nueva_relacion_2.getSelectedItem()){
            JOptionPane.showMessageDialog(this,"Ingrese una relación válida");
        }else{
            MatrizAdyacencia matriz=new MatrizAdyacencia();
            String relacion1=entry_nueva_relacion_1.getSelectedItem().toString();
            String relacion2=entry_nueva_relacion_2.getSelectedItem().toString();
            FuncionesGrafo fu = new FuncionesGrafo();
            fu.agregar_relacion(relacion1, relacion2);
            if (relacionExistente==true){
                JOptionPane.showMessageDialog(this,"Esta relación ya existe");
            }else{
                lbl1.setVisible(false);
                lbl2.setVisible(false);
                lbl3.setVisible(false);
                lbl4.setVisible(false);
                entry_nueva_relacion_1.setVisible(false);
                entry_nueva_relacion_2.setVisible(false);
                agg_rel_btn.setVisible(false);
                lbl_rel_agg.setVisible(true);
            }
        }  
    }//GEN-LAST:event_agg_rel_btnActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        v3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void entry_nueva_relacion_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entry_nueva_relacion_1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_entry_nueva_relacion_1ActionPerformed

    private void entry_nueva_relacion_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entry_nueva_relacion_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entry_nueva_relacion_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAgregarConexion(v3).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agg_rel_btn;
    private javax.swing.JButton atras;
    private javax.swing.JComboBox<String> entry_nueva_relacion_1;
    private javax.swing.JComboBox<String> entry_nueva_relacion_2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl_rel_agg;
    // End of variables declaration//GEN-END:variables
}
